### ISSUE TITLE
Yeoman configuration

### ISSUE THREAD

**Issue by bramsmulders** [colours/generator-patternlab-starterkit#34]
Project settings
- [x] Project name selection
- [x] Project folder selection
- [x] Gitignore

Development features

- [ ] [Blocss css framework](https://github.com/Blocss/)
- [x] Babel for ES2015, ES6 
- [x] Customizr for a lean mean modernizr machine
- [x] Enable choice between [starterkit-mustache-demo](https://github.com/pattern-lab/starterkit-mustache-demo) or [starterkit-colours-mustache](https://github.com/colours/starterkit-colours-mustache)
    - [ ] Template engine update based on chosen starterkit

**Comment by portfolioris** [comment]
Partially fixed in #42
