### ISSUE TITLE
Cannot GET /index.html

### ISSUE THREAD

**Issue by awasem** [colours/generator-patternlab-starterkit#43]
after initial download and run this is what I get ,,Cannot GET /index.html" how do I fix?

**Comment by portfolioris** [comment]
Hi @awasem, thank you for your interest in this tool. We haven't worked on this for a while, so some things are a little outdated. I will make some updates and fix this as soon as possible.

**Comment by portfolioris** [comment]
@awasem Can you check if it works for you now? Note: the install command has changed.

**Comment by awasem** [comment]
@portfolioris this worked thank you!!!!!!
