### ISSUE TITLE
Replace CSSLint with Stylelint

### ISSUE THREAD

**Issue by bramsmulders** [colours/generator-patternlab-starterkit#8]
http://stylelint.io/

To strictly enforce users to comply with with the code style.

**Comment by jeroenkampinga** [comment]
I've picked this issue up. Please check the pull request: ["Replace CSSLint with Stylelint"](https://github.com/colours/generator-patternlab-starterkit/pull/9).

**Comment by bramsmulders** [comment]
Fixed in v1.1
